name: Auto deploy to Github Pages
on: 
  watch:
    types: [started]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: "12.x"
    - name: Install dependencies
      run: npm install
    - name: Build website
      run: npm run build
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
